import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const giestMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-giest-sans",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Bugbook",
    default: "Bugbook",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${(geistSans.variable, giestMono.variable)}`}>
        {children}
      </body>
    </html>
  );
}
